---

- import_tasks: route53_info.yml
  when: route53_hosted_zone_id is undefined

- import_tasks: rhcos_ami_info.yml
  when: rhcos_ami is undefined

- name: Destroy infrastructure using Terraform
  terraform:
    project_path: "{{ role_path }}/terraform/aws"
    state: absent
    variables:
      cluster_name: "{{ cluster_name }}"
      base_domain: "{{ base_domain }}"
      cluster_domain: "{{ cluster_domain }}"
      cluster_id: "{{ cluster_id }}"
      vpc_cidr: "{{ vpc_cidr | default(omit) }}"
      rhcos_ami: "{{ rhcos_ami }}"
      keypair_name: "{{ keypair_name }}"
    workspace: "{{ terraform_workspace }}"
  register: r_terraform_apply
