---

- import_tasks: route53_info.yml
  when: route53_hosted_zone_id is undefined

- import_tasks: rhcos_ami_info.yml
  when: rhcos_ami is undefined

- name: Build infrastructure using Terraform
  terraform:
    project_path: "{{ role_path }}/terraform/aws"
    force_init: yes
    state: present
    variables:
      cluster_name: "{{ cluster_name }}"
      base_domain: "{{ base_domain }}"
      cluster_domain: "{{ cluster_domain }}"
      cluster_id: "{{ cluster_id }}"
      vpc_cidr: "{{ vpc_cidr | default(omit) }}"
      rhcos_ami: "{{ rhcos_ami }}"
      keypair_name: "{{ keypair_name }}"
      route53_hosted_zone_id: "{{ route53_hosted_zone_id }}"
    workspace: "{{ terraform_workspace }}"
  register: r_terraform_apply

- import_tasks: aws_info.yml

- name: Wait for bastion to boot
  wait_for:
    host: "{{ hostvars.bastion.ansible_host }}"
    port: 22
    search_regex: OpenSSH
  delegate_to: localhost
