---
# defaults file for infrastructure

terraform_workspace: "openshift-deploy-{{ cluster_name }}-{{ base_domain | replace('.', '-') }}"

cluster_id: "{{ cluster_name }}-{{ base_domain | hash('sha256') | regex_replace('^(\\w{5}).*', '\\1') }}"
cluster_domain: "{{ cluster_name }}.{{ base_domain }}"

vpc_cidr: 172.31.0.0/16
